  #Set true if you want a chat room created when create a meeting.
  create_muc: true
  
  #Set true to send xmpp update stanza when meeting/items get updated 
  send_xmpp_CRUD: true
  
  # XMPP server address e.g jabber.net
  xmpp_server: <TODO: XMPP.MYSERVER.COM>
  xmpp_bosh_port: 5280
  c2s_port: 5333
  
  # Credential used to create chat rooms
  username: <TODO:BACKEND-ADMIN-USERNAME>
  password: <TODO:BACKEND-ADMIN-PASSWORD>
  
  #Set true if you want a JID to be created on xmpp_server when users register on qworky site
  create_jid: true
  
  #Guest JIDs will be Guest<random-number>
  guest_jid: Juest
  
  #default password for user JIDs on xmpp_server
  default_pwd: <TODO: DEFAULT-GUEST-PASSWORD>
  
  #sub-domain for chat rooms
  muc_namespace: conference.<TODO: XMPP.MYSERVER.COM>
  
  #chat rooms are named [jegolizating_<ID>]
  muc_name_constant: jegolizing_
  
  #XMPP BOSH service url eg. relative url with rewriting /http-bind/, or absolute http://XMPP.MYSERVER.COM/http-bind/
  bosh_service: <TODO: BOSH-SERVICE-URL>